"""Fix JobRecord relationship with ApiToken

Revision ID: d84e53ced255
Revises: 1b863a2ef627
Create Date: 2025-04-06 01:22:17.386179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd84e53ced255'
down_revision: Union[str, None] = '1b863a2ef627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
