"""privilage added to token instead of user

Revision ID: 7fac5d715541
Revises: 9f20bb827495
Create Date: 2025-05-08 10:59:04.811147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7fac5d715541'
down_revision: Union[str, None] = '9f20bb827495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_privileges',
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('privilege_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['token_id'], ['api_tokens.token_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id', 'privilege_id')
    )
    op.drop_table('user_privileges')
    op.add_column('api_tokens', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('api_tokens', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('api_tokens_ibfk_1', 'api_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'api_tokens', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('documents_ibfk_1', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'jobs', ['job_id'], ['job_id'], ondelete='CASCADE')
    op.drop_constraint('jobs_ibfk_1', 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'api_tokens', ['api_token_id'], ['token_id'], ondelete='CASCADE')
    op.execute(
        "ALTER TABLE jobs MODIFY status ENUM('QUEUED','PROCESSING','COMPLETED','FAILED','COMPLETED_WITH_ERRORS') NOT NULL;"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key('jobs_ibfk_1', 'jobs', 'api_tokens', ['api_token_id'], ['token_id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_ibfk_1', 'documents', 'jobs', ['job_id'], ['job_id'])
    op.drop_constraint(None, 'api_tokens', type_='foreignkey')
    op.create_foreign_key('api_tokens_ibfk_1', 'api_tokens', 'users', ['user_id'], ['user_id'])
    op.drop_column('api_tokens', 'updated_at')
    op.drop_column('api_tokens', 'created_at')
    op.execute(
        "ALTER TABLE jobs MODIFY status ENUM('QUEUED','PROCESSING','COMPLETED','FAILED') NOT NULL;"
    )
    op.create_table('user_privileges',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('privilege_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], name='user_privileges_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='user_privileges_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('token_privileges')
    # ### end Alembic commands ###
