"""Added rescale_factor to DocumentRecord table

Revision ID: 9a96b8bd10a3
Revises: 7fac5d715541
Create Date: 2025-08-22 15:09:23.023129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a96b8bd10a3'
down_revision: Union[str, None] = '7fac5d715541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('rescale_factor', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'rescale_factor')
    # ### end Alembic commands ###
