"""Privilage tables added

Revision ID: 9f20bb827495
Revises: c7a593574dd7
Create Date: 2025-05-07 11:19:16.922610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9f20bb827495'
down_revision: Union[str, None] = 'c7a593574dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_privileges_id'), 'privileges', ['id'], unique=False)
    op.create_table('user_privileges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('privilege_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['privilege_id'], ['privileges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('api_tokens', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.alter_column('api_tokens', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_table('user_privileges')
    op.drop_index(op.f('ix_privileges_id'), table_name='privileges')
    op.drop_table('privileges')
    # ### end Alembic commands ###
