"""default value remove from documents.rescale_factor

Revision ID: ade9bba599f7
Revises: 9a96b8bd10a3
Create Date: 2025-08-22 17:55:53.224832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade9bba599f7'
down_revision: Union[str, None] = '9a96b8bd10a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
