"""default value 1.0 added to  documents.rescale_factor

Revision ID: c3553fd3d37b
Revises: ade9bba599f7
Create Date: 2025-08-22 18:09:10.232367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3553fd3d37b'
down_revision: Union[str, None] = 'ade9bba599f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
