"""added columns: documents.width, documents.height, jobs.n_documents

Revision ID: c7a593574dd7
Revises: 2fe43581ee8d
Create Date: 2025-04-09 12:44:49.931135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7a593574dd7'
down_revision: Union[str, None] = '2fe43581ee8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('width', mysql.SMALLINT(), nullable=True))
    op.add_column('documents', sa.Column('height', mysql.SMALLINT(), nullable=True))
    op.add_column('jobs', sa.Column('n_documents', mysql.SMALLINT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'n_documents')
    op.drop_column('documents', 'height')
    op.drop_column('documents', 'width')
    # ### end Alembic commands ###
