NUM_QUERIES = 200
MAX_LINES = 20


WANDB = True
VISUALIZE = False
PROJECT_NAME = f"TLDr2_large"
BRANCH_NAME = f"vit_rcda"
COMMIT_NAME = "Experiment1"
PATCH_SIZE = 256


PATCHES_VERSION = 7


BATCH_SIZE = 8
LR = 1e-5
NUM_CPUS = 9
NUM_EPOCHS = 1000


GEOM_COEFF = 0.3
POS_FOCAL_COEFF = 0.4
NEG_FOCAL_COEFF = 0.3


INF_MATCH_COST = 10000000
MATCH_GEOM_COEFF = 0.9
MATCH_CLS_COEFF = 0.1


DESC = f"{BRANCH_NAME}__{MATCH_CLS_COEFF}_{MATCH_GEOM_COEFF}__{POS_FOCAL_COEFF}_{NEG_FOCAL_COEFF}_{GEOM_COEFF}___{LR}"